language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - flex
            - bison
            - libreadline-dev

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - flex
            - bison
            - libreadline-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - flex
            - bison
            - libreadline-dev
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - flex
            - bison
            - libreadline-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - ./build_all.sh

notifications:
  email: false
